trigger:
  - main

pool:
  vmImage: 'ubuntu-22.04'  # Or ubuntu-22.04


steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt  # This won't fail even if the file is empty
    displayName: 'Install Dependencies'

  - script: |
      echo "Running Backend Script"
      python dbbackend.py
    displayName: 'Run Backend'

 
